Repository NCAR/CUPiD, pull requests merged in 2024-11, with the labels that each got.

#142 generate ADF config file
  helper_scripts/generate_adf_config_file.py
Labels: atm

#126 Adding a few rof notebooks
  README.md
  cupid/run.py
  examples/coupled_model/config.yml
  examples/key_metrics/config.yml
  examples/nblibrary/rof/global_discharge_gauge_compare_obs.ipynb
  examples/nblibrary/rof/global_discharge_ocean_compare_obs.ipynb
  examples/nblibrary/rof/scripts/colors.py
  examples/nblibrary/rof/scripts/metrics.py
  examples/nblibrary/rof/scripts/utility.py
  examples/nblibrary/rof/setup/large_river_50.txt
  examples/nblibrary/rof/setup/setup.yaml
Labels: enhancement, lnd

#156 Cleanup PR #2 (v2)
  NCARtips.md
  README.md
  cupid/clear.py
  cupid/cupid_webpage.py
  cupid/run_diagnostics.py
  cupid/run_timeseries.py
  cupid/timeseries.py
  docs/ContributorsGuide.md
  docs/addingnotebookstocollection.md
  environments/README
  environments/cupid-infrastructure.yml
  examples/external_diag_packages/config.yml
  examples/key_metrics/config.yml
  pyproject.toml
Labels: framework
