Repository NCAR/CUPiD, pull requests merged in 2025-07, with the labels that each got.

#248 Update RunCESM.md
  RunCESM.md
Labels: documentation

#217 Add remapping script
  cupid/remapping.py
  cupid/run_remapping.py
  examples/key_metrics/config.yml
  helper_scripts/generate_cupid_config_for_cesm_case.py
  pyproject.toml
Labels: high priority, common utility

#255 Fix multiple sel functions for ds1_lab
  nblibrary/ice/Hemis_seaice_visual_compare_obs_lens.ipynb
Labels: bug

#223 Addition of Time Series Directory Option
  .github/PULL_REQUEST_TEMPLATE.md
  cime_config/config_tool.xml
  cupid/run_timeseries.py
  examples/additional_metrics/config.yml
  examples/external_diag_packages/config.yml
  examples/key_metrics/config.yml
  helper_scripts/cesm_postprocessing.sh
  helper_scripts/generate_adf_config_file.py
  helper_scripts/generate_cupid_config_for_cesm_case.py
  nblibrary/atm/Global_PSL_NMSE_compare_obs_lens.ipynb
  nblibrary/ice/Hemis_seaice_visual_compare_contour.ipynb
  nblibrary/ice/Hemis_seaice_visual_compare_obs_lens.ipynb
  nblibrary/lnd/Global_TerrestrialCouplingIndex_VisualCompareObs.ipynb
Labels: enhancement, framework, high priority
