Repository NCAR/CUPiD, pull requests merged in 2025-01, with the labels that each got.

#157 A few additions for the sea ice.
  examples/coupled_model/config.yml
  examples/key_metrics/config.yml
  nblibrary/ice/Hemis_seaice_visual_compare_full.ipynb
  nblibrary/ice/Hemis_seaice_visual_compare_obs_lens.ipynb
  nblibrary/ice/cice_vars.yml
  nblibrary/ice/cice_vars_full.yml
  nblibrary/ice/plot_diff.py
  nblibrary/ice/vect_diff.py
Labels: cice

#164 Cleanup in response to failed CESM Workflow
  cupid/run_timeseries.py
Labels: framework, common utility

#162 Fix some titles and get the full sea ice diagnostics working again
  examples/coupled_model/config.yml
  nblibrary/ice/Hemis_seaice_visual_compare_contour.ipynb
  nblibrary/ice/Hemis_seaice_visual_compare_full.ipynb
  nblibrary/ice/Hemis_seaice_visual_compare_obs_lens.ipynb
Labels: cice

#171 Fix ILAMB installation error
  environments/cupid-analysis.yml
Labels: bug
