Repository NCAR/CUPiD, pull requests merged in 2025-02, with the labels that each got.

#182 Add in CESM2 and CESM1 LENS data and fix axes in sea ice plots.
  nblibrary/ice/Hemis_seaice_visual_compare_contour.ipynb
  nblibrary/ice/Hemis_seaice_visual_compare_obs_lens.ipynb
  nblibrary/ice/plot_diff.py
Labels: cice

#184 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#188 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#165 Include ILAMB output in notebook and provide link to full diagnostic package
  cupid/cupid_webpage.py
  examples/.gitignore
  examples/external_diag_packages/config.yml
  examples/ilamb/.gitignore
  examples/ilamb/ilamb_nohoff_final_CLM.cfg
  examples/ilamb/test_run.sh
  examples/key_metrics/config.yml
  helper_scripts/.gitignore
  helper_scripts/generate_cupid_config_for_cesm_case.py
  helper_scripts/generate_ilamb_config_files.py
  ilamb_aux/.gitignore
  ilamb_aux/ilamb_nohoff_final_CLM_BGC_template.cfg
  ilamb_aux/ilamb_nohoff_final_CLM_SP_template.cfg
  nblibrary/lnd/link_to_ILAMB.ipynb
  nblibrary/lnd/model_setup.txt
Labels: lnd

#191 Include global level obs repo directory
  examples/external_diag_packages/config.yml
  examples/key_metrics/config.yml
  nblibrary/atm/Global_PSL_NMSE_compare_obs_lens.ipynb
  nblibrary/glc/Greenland_SMB_visual_compare_obs.ipynb
  nblibrary/ice/Hemis_seaice_visual_compare_obs_lens.ipynb
  nblibrary/lnd/Global_TerrestrialCouplingIndex_VisualCompareObs.ipynb
Labels: common utility
